[package]
name = "entrait"
version = "0.3.0"
authors = ["Audun Halland <audun.halldand@pm.me>"]
edition = "2021"
license = "MIT"
description = "The entrait macro"
repository = "https://github.com/audunhalland/entrait/"
keywords = ["ioc", "di", "procedural-macro", "macros"]

[dependencies]
entrait_macros = { path = "entrait_macros", version = "0.3.0" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
async-trait = "0.1"
unimock = "0.2"
mockall = "0.11"
implementation = "0.1"
feignhttp = "0.4"
