[package]
name = "entrait"
version = "0.1.0"
authors = ["Audun Halland <audun.halldand@pm.me>"]
edition = "2021"
license = "MIT"
description = "The entrait macro"

[dependencies]
syn = { version = "1.0.75", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[features]
async_trait = []

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

[lib]
proc-macro = true
