[package]
name = "entrait"
version = "0.1.0"
authors = ["Audun Halland <audun.halldand@pm.me>"]
edition = "2021"
license = "MIT"
description = "Traiten macro definitions"

[dependencies]
syn = { version = "1.0.75", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[lib]
proc-macro = true
