[package]
name = "entrait"
version = "0.0.2"
authors = ["Audun Halland <audun.halldand@pm.me>"]
edition = "2021"
license = "MIT"
description = "The entrait macro"
repository = "https://github.com/audunhalland/entrait/"
keywords = ["ioc", "di", "procedural-macro", "macros"]

[dependencies]
syn = { version = "1.0.75", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[features]
async_trait = []

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
mockall = "0.11"

[lib]
proc-macro = true
