[package]
name = "entrait_macros"
version = "0.1.0"
authors = ["Audun Halland <audun.halldand@pm.me>"]
edition = "2021"
license = "MIT"
description = "Procedural macros reexported by entrait"
repository = "https://github.com/audunhalland/entrait/"
keywords = []

[dependencies]
syn = { version = "1.0.75", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
mockall = "0.11"

[lib]
proc-macro = true
