name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-hack
      - name: Test feature powerset
        run: cargo hack --feature-powerset --optional-deps "unimock" --exclude-features "default use-associated-future nightly-tests" --exclude-no-default-features test
      - name: Test workspace
        run: cargo test --workspace --features "async-trait"

  test-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - name: Test nightly features
        run: cargo hack --feature-powerset --optional-deps "unimock" --exclude-features "default use-async-trait" --exclude-no-default-features test
