name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-hack
      - name: Test
        run: cargo hack --feature-powerset --group-features "unimock use-async-trait" --optional-deps "unimock" --exclude-features "use-associated-future nightly-tests" test

  test-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - name: Test nightly features
        run: cargo test --workspace --features "unimock async-trait nightly-tests"
